- name: Install pip
  yum:
    name: ['epel-release', 'python-pip']
    state: latest

- name: Upgrade pip
  pip:
    name: pip
    state: latest

- name: Install docker
  pip:
    name: docker
    state: latest

- name: Enable docker server
  systemd:
    name: docker
    state: started
    enabled: yes

- name: Copy docker directory to installdir
  copy: src=/var/lib/docker dest={{ install_dir }}/ remote_src=yes

- name: Create a symbolic link
  file:
    src: "{{ install_dir }}/docker"
    dest: /var/lib/docker
    owner: root
    group: root
    state: link
  notify: Reload systemd

- name: Start docker server
  systemd:
    name: docker
    state: started

- name: Creating PMM Data Container
  docker_container:
    name: pmm-data
    image: percona/pmm-server:latest
    state: present
    volumes:
    - /opt/prometheus/data
    - /opt/consul-data
    - /var/lib/mysql
    - /var/lib/grafana
    command: /bin/true

- name: Running PMM Data Container secured with pmm_server_username and pmm_server_password
  docker_container:
    name: pmm-server
    image: percona/pmm-server:latest
    state: started
    volumes_from:
    - pmm-data
    env: "{{ __pmm_server_env }}"
    ports:
    - "{{ pmm_server_http_port }}:80"
    restart_policy: always