- name: Create a directory for monitor
  file: >
        path={{ monitordir }} state=directory owner=mysql group=mysql
        path={{ shelldir }} state=directory owner=mysql group=mysql

- name: Rendering monitor script file
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: mysql
    group: mysql
    mode: 0744
  with_items:
    - { src: 'alert_mgr_status.sh.j2', dest: "{{ shelldir }}/alert_mgr_status.sh" }
    - { src: 'alert_slave_status.sh.j2', dest: "{{ shelldir }}/alert_slave_status.sh" }
  when: ansible_hostname == "slave_monitor1" or
        ansible_hostname == "slave_monitor2" or
        ansible_hostname == "slave1" or
        ansible_hostname == "proxysql2"

- name: Add automatic monitor mgr&slave schedule for slave_monitor1
  cron:
    name: "automatic monitor mgr&slave"
    minute: "*/2"
    hour: "*"
    job: "{{ item }}"
  with_items:
    - {{ shelldir }}/alert_mgr_status.sh > /dev/null
    - {{ shelldir }}/alert_slave_status.sh > /dev/null
  when: ansible_hostname == "slave_monitor1"

- name: Add automatic monitor mgr&slave schedule for slave_monitor2
  cron:
    name: "automatic monitor mgr&slave"
    minute: "*/3"
    hour: "*"
    job: "{{ item }}"
  with_items:
    - {{ shelldir }}/alert_mgr_status.sh > /dev/null
    - {{ shelldir }}/alert_slave_status.sh > /dev/null
  when: ansible_hostname == "slave_monitor2"

- name: Add automatic slave schedule for slave1
  cron:
    name: "automatic monitor slave"
    minute: "*/2"
    hour: "*"
    job: "{{ item }}"
  with_items:
    - {{ shelldir }}/alert_slave_status.sh > /dev/null
  when: ansible_hostname == "slave1"

- name: Add automatic slave schedule for slave2
  cron:
    name: "automatic monitor slave"
    minute: "*/3"
    hour: "*"
    job: "{{ item }}"
  with_items:
    - {{ shelldir }}/alert_slave_status.sh > /dev/null
  when: ansible_hostname == "slave2"

- name: Rendering mysql_slow_collect_send.sh script file
  template:
    src: mysql_slow_collect_send.sh.j2
    dest: "{{ shelldir }}/mysql_slow_collect_send.sh"
    owner: root
    group: root
    mode: 0744
  when: ansible_hostname == "ansible"

- name: Copy the mail body file and example file
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - { src: 'main_body.txt', dest: "{{ monitordir }}/main_body.txt" }
    - { src: 'slow_digest_example.docx', dest: "{{ monitordir }}/slow_digest_example.docx" }
  when: ansible_hostname == "ansible"

- name: ADD automatically collect slow logs and send them to DBA via email
  cron:
    name: "automatically collect slow logs and send them to DBA via email"
    minute: "10"
    hour: "09"
    job: "{{ shelldir }}/mysql_slow_collect_send.sh > /dev/null"
  when: ansible_hostname == "ansible"