- name: Remove orphaned services
  shell: "pmm-admin repair"

- name: Config pmm server via pmm-admin
  shell: "pmm-admin config --server ansible:{{ pmm_server_http_port }} --server-user pmm --server-password '{{ mysql_monitor_password }}'"

- name: Add mysql via pmm-admin for mgr&slave_monitor&mysql group
  shell: "pmm-admin add mysql --user pmm --password '{{ pmm_password }}'"
  when: >
        ( ansible_hostname not in groups.proxysql_pro1 ) and
        ( ansible_hostname not in groups.proxysql_pro2 )

- name: Add proxysql via pmm-admin for proxysql group
  shell: "{{ item }}"
  with_items:
    - pmm-admin add proxysql:metrics --dsn "stats:stats@tcp(localhost:6032)/"
    - pmm-admin add linux:metrics
  when: >
        ( ansible_hostname in groups.proxysql_pro1 ) or
        ( ansible_hostname in groups.proxysql_pro2 )