- name: Stop docker server
  systemd:
    name: docker
    state: stopped

- name: Uninstall docker
  yum:
   name: docker
   state: absent

- name: Remove docker directory
  file:
    path: /var/lib/docker
    state: absent

- name: Install docker
  yum:
    name: docker
    state: latest

- name: Enable docker server
  systemd:
    name: docker
    state: started
    enabled: yes

- name: Start docker server
  systemd:
    name: docker
    state: started

- name: Stop docker server
  systemd:
    name: docker
    state: stopped

- name: Copy docker directory to installdir
  copy: src=/var/lib/docker dest={{ install_dir }} remote_src=yes

- name: Config Docker Root Dir
  template:
    dest: /etc/docker/daemon.json
    src: daemon.json.j2
    owner: root
    group: root
    mode: '0644'

- name: Start docker server
  systemd:
    name: docker
    state: started

- name: Docker pull image
  shell: "docker pull percona/pmm-server:latest"

- name: Docker create container
  shell: "docker create -v /opt/prometheus/data -v /opt/consul-data -v /var/lib/mysql -v /var/lib/grafana --name pmm-data percona/pmm-server:latest /bin/true"

- name: Dcoer run container
  shell: "docker run -d -p {{ pmm_server_http_port }}:80 --volumes-from pmm-data --name pmm-server -e SERVER_USER=pmm -e SERVER_PASSWORD='{{ mysql_monitor_password }}' --restart always percona/pmm-server:latest"
