- name: Rendering config_replication_group.sh.j2
  template:
    src: config_replication_group.sh.j2
    dest: "{{ shelldir }}/config_replication_group.sh"
    owner: root
    group: root
    mode: 0744

- name: Config group_replication_bootstrap_group
  shell: "sh -x {{ shelldir }}/config_replication_group.sh '{{ root_password }}' '{{ mysql_monitor_password }}' >> /tmp/group_replication.log"

- name: Wait the member status
  pause: seconds=5

- name: Show the MEMBER_STATE
  community.mysql.mysql_query:
    login_port: "{{ mysql_port }}"
    login_user: root
    login_password: "{{ root_password }}"
    login_unix_socket: "{{ socket }}"
    query: SELECT MEMBER_STATE FROM performance_schema.replication_group_members where MEMBER_ID=@@server_uuid

- name: Check the member status
  pause: seconds=10