- name: Rendering config_replication_group.sh.j2
  template:
    src: config_replication_group.sh.j2
    dest: "{{ shelldir }}/config_replication_group.sh"
    owner: root
    group: root
    mode: 0744

- name: Set group_replication_start_on_boot=on
  replace:
    path: "{{ etcdir }}/my_{{ mysql_port }}.cnf"
    regexp: 'loose-group_replication_start_on_boot = off'
    replace: 'loose-group_replication_start_on_boot = on'

- name: Copy the mgr_monitor.sql
  copy: src=mgr_monitor_official.sql dest=/tmp
  when: ansible_hostname == "{{ primary_hostname }}"

- name: Config group_replication_bootstrap_group
  shell: "sh -x {{ shelldir }}/config_replication_group.sh '{{ root_password }}' '{{ mysql_monitor_password }}'"