- name: Install mysql-router
  yum:
    name: mysql-router-community.x86_64
    state: latest

- name: Create directories for mysql-router
  file: path={{ item }} state=directory owner=mysqlrouter group=mysqlrouter
  with_items:
    - "{{ routerdir}}"

- name: Rendering mysqlrouter service file
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: mysql
    group: mysql
    mode: 0644
  with_items:
    - { src: 'mysqlrouter.service.j2', dest: '/usr/lib/systemd/system/mysqlrouter_{{ mysql_port }}.service' }

- name: Force systemd to reread configs
  systemd:
    daemon_reload: yes

- name: Case sensitive password string match for bootstrap mysqlrouter
  expect:
    command: "mysqlrouter --user=mysqlrouter --bootstrap root@127.0.0.1:{{ mysql_port }} --directory {{ routerdir}}/{{ env }} --conf-use-sockets \
    --account repl --account-host {{ ansible_default_ipv4.network }}/24 \
    --conf-set-option=logger.level=warning \
    --conf-set-option=default.max_total_connections={{ max_connections }} \
    --conf-set-option=default.max_connections={{ max_connections }} \
    --conf-set-option=connection_pool.max_idle_server_connections={{ (max_connections) // 10 }} \
    --conf-set-option=connection_pool.idle_timeout={{ timeout }} \
    --conf-set-option=routing:bootstrap_rw_split.connection_sharing=1 \
    --conf-set-option=routing:bootstrap_rw_split.connection_sharing_delay=100 \ 
    --conf-set-option=routing:bootstrap_rw_split.max_connect_errors={{ (max_connections) * 10 }} \
    --force"
    responses:
      (?i)root: "{{ root_password }}"
      (?i)repl: "{{ mysql_monitor_password }}"
    echo: yes
  #no_log: True

- name: Start mysqlrouter
  systemd:
    name: mysqlrouter_{{ mysql_port }}
    state: restarted

- name: Enable mysqlrouter
  systemd:
    name: mysqlrouter_{{ mysql_port }}
    enabled: yes