- name: Config replication for master
  mysql_replication:
    login_port: "{{ mysql_port }}"
    login_user: root
    login_password: "{{ root_password }}"
    login_unix_socket: "{{ socket }}"
    mode: changemaster
    master_host: master
    master_port: "{{ mysql_port }}"
    master_user: repl
    master_password: "{{ mysql_monitor_password }}"
    master_auto_position: yes
  when: ansible_hostname != "master"

- name: Start slave status for slaves
  mysql_replication:
    login_port: "{{ login_port }}"
    login_user: root
    login_password: "{{ root_password }}"
    login_unix_socket: "{{ socket }}"
    mode: startslave
  when: ansible_hostname != "master"