- name: Rendering config_cluster.js.j2
  template:
    src: config_cluster.js.j2
    dest: "{{ shelldir }}/config_cluster.js"
    owner: root
    group: root
    mode: 0644
  when: ansible_hostname == "{{ primary_hostname }}"

- name: Config innodb cluster
  shell: "sudo /usr/bin/mysqlsh root@{{ primary_hostname }}:{{ mysql_port }} --password='{{ root_password }}' -f {{ shelldir }}/config_cluster.js"
  when: ansible_hostname == "{{ primary_hostname }}"

- name: Wait the member status
  pause: seconds=5

- name: Show the MEMBER_STATE
  community.mysql.mysql_query:
    login_port: "{{ mysql_port }}"
    login_user: root
    login_password: "{{ root_password }}"
    login_unix_socket: "{{ socket }}"
    query: SELECT MEMBER_STATE FROM performance_schema.replication_group_members where MEMBER_ID=@@server_uuid

- name: Check the member status
  pause: seconds=10
  
- name: Set auto_increment_offset=1 for secondry
  community.mysql.mysql_variables:
    login_port: "{{ mysql_port }}"
    login_user: root
    login_password: "{{ root_password }}"
    login_unix_socket: "{{ socket }}"
    variable: "{{ item.original }}"
    value: "{{ item.change }}"
    mode: persist
  with_items:
    - { original: 'super_read_only', change: '0' }
    - { original: 'auto_increment_offset', change: '1' }
    - { original: 'super_read_only', change: '1' }
  when: ansible_hostname != "{{ primary_hostname }}"
    
- name: Set auto_increment_offset=1 for primary
  community.mysql.mysql_variables:
    login_port: "{{ mysql_port }}"
    login_user: root
    login_password: "{{ root_password }}"
    login_unix_socket: "{{ socket }}"
    variable: auto_increment_offset
    value: 1
    mode: persist
  when: ansible_hostname == "{{ primary_hostname }}"
  
- name: Check for auto_increment_offset setting
  community.mysql.mysql_variables:
    login_port: "{{ mysql_port }}"
    login_user: root
    login_password: "{{ root_password }}"
    login_unix_socket: "{{ socket }}"
    variable: auto_increment_offset

- name: Check the auto_increment_offset setting
  pause: seconds=10
