- name: Rendering config_replication_group.sh.j2
  template:
    src: config_replication_group.sh.j2
    dest: "{{ shelldir }}/config_replication_group.sh"
    owner: root
    group: root
    mode: 0744

- name: Config group_replication_bootstrap_group
  shell: "sh -x {{ shelldir }}/config_replication_group.sh '{{ root_password }}' '{{ mysql_monitor_password }}'"