- name: Copy the percona-release package and mydumper package
  copy:
    src: "{{ item }}"
    dest: "{{ package_dir }}"
  with_items:
    - percona-release-0.1-6.noarch.rpm
    - mydumper-0.9.5-2.el7.x86_64.rpm

- name: Install the percona-release package and mydumper package
  yum:
    name: ["{{ package_dir }}/percona-release-0.1-6.noarch.rpm", "{{ package_dir }}/mydumper-0.9.5-2.el7.x86_64.rpm"]
    state: present

- name: Copy the percona-release.repo
  copy: src=percona-release.repo dest=/etc/yum.repos.d/percona-release.repo

- name: Install the percona tools
  yum:
    name: "{{ tools }}"
  vars:
    tools:
    - percona-toolkit.x86_64
    - percona-xtrabackup-80.x86_64
    - pmm-client.x86_64
    state: latest
  register: result
  retries: 7
  until: result is succeeded
