---
# tasks file for mysql_ray
- include: password.yml
  when: not is_update
 
- include: system_check.yml
  when: not is_update

- include: initial_start.yml
  when: not is_update and is_standalone

- include: initial_group_replication.yml
  when: not is_update and mysql_group_replication

- include: initial_replication.yml
  when: not is_update and mysql_traditional_replication

- include: install_tools.yml
  when: not is_update and percona_tools

- include: auto_xtrabackup.yml
  when: not is_update and auto_xtrabackup

- include: upgrade.yml
  when: is_update
