---
# tasks file for mysql_ray
- include: password.yml
  when: not is_update

- include: system_check.yml
  when: not is_update

- include: initial_start.yml
  when: is_standalone

- include: initial_group_replication.yml
  when: mysql_group_replication

- include: initial_replication.yml
  when: mysql_traditional_replication

- include: install_tools.yml
  when: percona_tools

- include: auto_xtrabackup.yml
  when: auto_xtrabackup

- include: auto_monitor.yml
  when: auto_monitor

- inclued: auto_pmm.yml
  when: auto_pmm

- include: upgrade.yml
  when: is_update