---
# tasks file for mysql_ray
- include: password.yml
  when: ( is_standalone | default(False) ) or ( auto_pmm | default(False) ) or ( auto_config_pmm | default(False) )

- include: system_check.yml
  when: is_standalone | default(False) or ( upgrade_my_cnf | default(False) )

- include: initial_start.yml
  when: is_standalone | default(False)

- include: initial_group_replication.yml
  when: ( is_standalone | default(False) ) and ( mysql_group_replication | default(False) )

- include: initial_slave_monitor.yml
  when: ( is_standalone | default(False) ) and ( slave_monitor_replication | default(False) )

- include: upgrade_my_cnf.yml
  when: upgrade_my_cnf | default(False)

- include: upgrade_server.yml
  when: upgrade_server | default(False)