---
# tasks file for mysql_ray
- include: password.yml
  when: ( is_standalone | default(False) ) or ( innodb_cluster | default(False) ) or
        ( mysql_group_replication | default(False) ) or ( slave_monitor_replication | default(False) ) or
        ( upgrade_server | default(False) )

- include: system_check.yml
  when: is_standalone | default(False)

- include: initial_start.yml
  when: is_standalone | default(False)

- include: initial_group_replication.yml
  when: mysql_group_replication | default(False)

- include: initial_innodb_cluster.yml
  when: innodb_cluster | default(False)

- include: initial_slave_monitor.yml
  when: slave_monitor_replication | default(False)

- include: upgrade_my_cnf.yml
  when: upgrade_my_cnf | default(False)

- include: upgrade_server.yml
  when: upgrade_server | default(False)