- name: Copy the latest mysql
  copy: 
    src: "{{ mysql_upgrade_package }}"
    dest: "{{ package_dir }}"

- name: 解压安装包
  unarchive:
    src: "{{ package_dir }}/{{ mysql_upgrade_package }}"
    dest: "{{ package_dir }}"
    remote_src: yes
  run_once: True

- name: 停止mysql服务
  systemd:
    name: mysqld
    state: stopped

- name: 复制mysql二进制包
  copy:
    src: "{{ package_dir }}/{{ mysql_upgrade_version }}/"
    dest: "{{ basedir }}"
    remote_src: yes

- name: 启动mysql服务
  systemd:
    name: mysqld
    state: started
  notify: Set default_collation_for_utf8mb4 variable to utf8mb4_general_ci