- name: Copy the latest mysql
  copy:
    src: "{{ mysql_upgrade_package }}"
    dest: "{{ package_dir }}"

- name: Decompression package
  unarchive:
    src: "{{ package_dir }}/{{ mysql_upgrade_package }}"
    dest: "{{ package_dir }}"
    remote_src: yes
  run_once: True

- name: Stop mysql server
  systemd:
    name: mysqld
    state: stopped

- name: Copy the upgrade package
  shell: "cp -rf {{ package_dir }}/{{ mysql_upgrade_version }}/* {{ basedir }}/"

- name: Start mysql server
  systemd:
    name: mysqld
    state: started